### ISSUE TITLE
Compile time errors in rl4j related packages

### ISSUE THREAD

**Issue by gowthamnatarajan** [rubenfiszel/rl4j-examples#2]
https://github.com/deeplearning4j/gym-java-client/issues/4
https://github.com/deeplearning4j/rl4j/issues/9

I have created these 2 issues which will cause rl4j to not compile. Can you reply to that?

**Comment by rubenfiszel** [comment]
Hello,

Those errors come from commits from Skymind's team. My internship ended and I am not working with Skymind anymore. I do not have the bandwidth to fix their updates. You should contact them directly.

Best,

**Comment by huitseeker** [comment]
@rubenfiszel This might be closeable since both issues are difficult to reproduce after the 0.6 release (I've annotated each). 
On the larger issue of rl4j-examples, is there any chances you'd consider [transferring](https://help.github.com/articles/about-repository-transfers/) the repo to the dl4j (not skymind) org ? The community could use the examples, and maybe there's a chance to find some maintenance effort there if you don't have the free cycles for it ?

**Comment by rubenfiszel** [comment]
Good to know.
Oh yes of course, I don't mind transferring at all. This is on my github
out of convenience more than anything. I believe that Adam will integrate
it into the dl4j-examples repo :)
Anyway, the more community there is around rl4j, the happier I am.

Ruben Fiszel

2016-09-25 19:36 GMT+02:00 François Garillot notifications@github.com:
